baseURL = "https://approvedthoughts.com"
title = "Approved Thoughts"
theme = "hextra"

[params]
  description = "Welcome to Approved Thoughts"
  displayUpdatedDate = true
  
  [params.search]
    enable = true
    
  [params.sidebar]
    enable = true

[menu]
  [[menu.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 1
  [[menu.main]]
    name = "Archives"
    pageRef = "/archives"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
