baseURL = 'https://approvedthoughts.com/'
languageCode = 'en-us'
title = 'Approved Thoughts'
theme = 'hextra'

# Enable blog functionality
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

[markup.highlight]
  noClasses = false
  
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  #[[menu.main]]
  #  name = "Archives"
  #  url = "/archives/"
  #  weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
  # Main page settings
  description = ""
  mainSections = ['posts', 'blog']
  showFullContent = true
  
  # Site footer configuration
  copyright = "© 2023-2025 Approved Thoughts"
  
  [params.social]
    github = "apoorvtrivedi"
    # Add other social links if needed
    # twitter = "yourusername"
    # linkedin = "yourusername"

  # Hextra specific settings
  [params.hextra]
    [params.hextra.navbar]
      enable = true
      
    [params.hextra.footer]
      enable = true
      
    [params.hextra.theme]
      # Primary color of the theme
      # Type: string
      # Default: "#0055FF"
      primaryColor = "#4F46E5"
