backend:
  name: github
  repo: apoorvtrivedi/approvedthoughts
  branch: main
  base_url: https://api.staticcms.org
  auth_endpoint: auth

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean, default: true}
      - {label: Body, name: body, widget: markdown}